apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sgx-plugin
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
    verbs:
      - get
      - list
      - patch