apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sgx-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sgx-plugin
subjects:
  - kind: ServiceAccount
    name: sgx-plugin
    namespace: kube-system